use serde::{Deserialize, Serialize};
use std::fmt;

/// 47 typed relation types for the semantic graph.
/// Atom(subject) --RelationType--> Atom(object)
/// Surface text = function(RelationType, ObjectCase, morphology)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RelationType {
    RelPresupposes,
    RelLimitedBy,
    RelRequires,
    RelClaims,
    RelVerifiedBy,
    RelSignals,
    RelExpresses,
    RelDiffersFrom,
    RelRelatedTo,
    RelPreserves,
    RelOrientsToward,
    RelPrescribes,
    RelDenotes,
    RelStructures,
    RelDetermines,
    RelTransforms,
    RelTransformsInto,
    RelCreatedFrom,
    RelGives,
    RelReveals,
    RelRecognizes,
    RelUnifies,
    RelConnects,
    RelPrecedes,
    RelDependsOn,
    RelIncludes,
    RelEvokes,
    RelMeans,
    RelSays,
    RelNegates,
    RelDirectedAt,
    RelPointsTo,
    RelMakes,
    RelSupports,
    RelSets,
    RelDestroys,
    RelContrastsWith,
    RelNotReducibleTo,
    RelIsNot,
    RelIsA,
    RelNecessaryFor,
    RelReliesOn,
    RelCapableOf,
    RelCanBe,
    RelBuiltThrough,
    RelReconstructs,
    RelNotJustCopies,
}

impl RelationType {
    pub const ALL: [RelationType; 47] = [
        RelationType::RelPresupposes,
        RelationType::RelLimitedBy,
        RelationType::RelRequires,
        RelationType::RelClaims,
        RelationType::RelVerifiedBy,
        RelationType::RelSignals,
        RelationType::RelExpresses,
        RelationType::RelDiffersFrom,
        RelationType::RelRelatedTo,
        RelationType::RelPreserves,
        RelationType::RelOrientsToward,
        RelationType::RelPrescribes,
        RelationType::RelDenotes,
        RelationType::RelStructures,
        RelationType::RelDetermines,
        RelationType::RelTransforms,
        RelationType::RelTransformsInto,
        RelationType::RelCreatedFrom,
        RelationType::RelGives,
        RelationType::RelReveals,
        RelationType::RelRecognizes,
        RelationType::RelUnifies,
        RelationType::RelConnects,
        RelationType::RelPrecedes,
        RelationType::RelDependsOn,
        RelationType::RelIncludes,
        RelationType::RelEvokes,
        RelationType::RelMeans,
        RelationType::RelSays,
        RelationType::RelNegates,
        RelationType::RelDirectedAt,
        RelationType::RelPointsTo,
        RelationType::RelMakes,
        RelationType::RelSupports,
        RelationType::RelSets,
        RelationType::RelDestroys,
        RelationType::RelContrastsWith,
        RelationType::RelNotReducibleTo,
        RelationType::RelIsNot,
        RelationType::RelIsA,
        RelationType::RelNecessaryFor,
        RelationType::RelReliesOn,
        RelationType::RelCapableOf,
        RelationType::RelCanBe,
        RelationType::RelBuiltThrough,
        RelationType::RelReconstructs,
        RelationType::RelNotJustCopies,
    ];

    pub fn verb_ru(&self) -> &'static str {
        match self {
            RelationType::RelPresupposes => "предполагает",
            RelationType::RelLimitedBy => "ограничена",
            RelationType::RelRequires => "требует",
            RelationType::RelClaims => "претендует на",
            RelationType::RelVerifiedBy => "проверяется через",
            RelationType::RelSignals => "сигнализирует",
            RelationType::RelExpresses => "выражает",
            RelationType::RelDiffersFrom => "отличается от",
            RelationType::RelRelatedTo => "связана с",
            RelationType::RelPreserves => "сохраняет",
            RelationType::RelOrientsToward => "ориентирует на",
            RelationType::RelPrescribes => "предписывает",
            RelationType::RelDenotes => "обозначает",
            RelationType::RelStructures => "структурирует",
            RelationType::RelDetermines => "определяет",
            RelationType::RelTransforms => "преобразует",
            RelationType::RelTransformsInto => "преобразуется в",
            RelationType::RelCreatedFrom => "создаётся из",
            RelationType::RelGives => "придаёт",
            RelationType::RelReveals => "обнаруживает",
            RelationType::RelRecognizes => "признаёт",
            RelationType::RelUnifies => "объединяет",
            RelationType::RelConnects => "связывает",
            RelationType::RelPrecedes => "предшествует",
            RelationType::RelDependsOn => "зависит от",
            RelationType::RelIncludes => "включает",
            RelationType::RelEvokes => "вызывает",
            RelationType::RelMeans => "означает",
            RelationType::RelSays => "говорит",
            RelationType::RelNegates => "отрицает",
            RelationType::RelDirectedAt => "направлена на",
            RelationType::RelPointsTo => "указывает на",
            RelationType::RelMakes => "делает",
            RelationType::RelSupports => "поддерживает",
            RelationType::RelSets => "задаёт",
            RelationType::RelDestroys => "разрушает",
            RelationType::RelContrastsWith => "контрастирует с",
            RelationType::RelNotReducibleTo => "не сводится к",
            RelationType::RelIsNot => "не является",
            RelationType::RelIsA => "является",
            RelationType::RelNecessaryFor => "необходима для",
            RelationType::RelReliesOn => "опирается на",
            RelationType::RelCapableOf => "способна на",
            RelationType::RelCanBe => "может быть",
            RelationType::RelBuiltThrough => "строится через",
            RelationType::RelReconstructs => "реконструирует",
            RelationType::RelNotJustCopies => "не просто копирует",
        }
    }
}

impl fmt::Display for RelationType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
