//! Embedded Russian adjective lexicon, digest-pinned.
//!
//! Generated by `scripts/generate_adjective_lexicon.py` from the pymorphy3
//! OpenCorpora dictionary (see `data/adjective_manifest.json`). Full
//! attributive grid (`{case}_{m,f,n,pl}`), short predicative forms
//! (`short_{m,f,n,pl}`) for qualitative adjectives and the comparative cell
//! (`comp`) where the paradigm has one. The bundle is embedded, verified
//! against a compile-time SHA-256 and parsed once per process — the same
//! policy as the noun and verb lexicon bundles.
//!
//! The lexicon exists so that adjective surfaces in topics and quarantined
//! corpus rows stop being lexical gaps: lemmatization resolves them, and the
//! V2 realization can verify short-form agreement against the table instead
//! of trusting a pinned string.

use qxfx0_types::morphology::{Case, Gender, Number};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::sync::OnceLock;

const ADJECTIVE_LEXICON_BYTES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../data/adjective_lexemes.json"
));

/// SHA-256 of `data/adjective_lexemes.json`, printed by the generator.
const ADJECTIVE_LEXICON_SHA256: &str =
    "52e204deaa2566712a0588f04b58d02a0252d17ddbaa15e14af3066904fe692c";

const ADJECTIVE_LEXICON_SCHEMA: &str = "qxfx0:adjective-lexicon:v1";

#[derive(Debug, Deserialize)]
struct AdjectiveLexiconFile {
    schema: String,
    lemma_count: usize,
    lemmas: Vec<AdjectiveEntry>,
}

/// One adjective's materialized cells.
#[derive(Debug, Clone, Deserialize)]
pub struct AdjectiveEntry {
    pub lemma: String,
    pub forms: BTreeMap<String, String>,
}

/// Outcome of resolving a surface back to an adjective lemma.
///
/// Ambiguous surfaces (two lemmas share the form) deliberately do not pick a
/// winner: choosing one would fabricate a reading.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SurfaceLemma {
    Unique(&'static str),
    Ambiguous,
    Unknown,
}

impl AdjectiveEntry {
    pub fn form(&self, key: &str) -> Option<&str> {
        self.forms.get(key).map(String::as_str)
    }

    /// Short predicative form for the agreement features, when the paradigm
    /// has one (relational adjectives carry no short forms).
    pub fn short_form(&self, gender: Gender, number: Number) -> Option<&str> {
        let key = match (number, gender) {
            (Number::Plural, _) => "short_pl",
            (Number::Singular, Gender::Masculine) => "short_m",
            (Number::Singular, Gender::Feminine) => "short_f",
            (Number::Singular, Gender::Neuter) => "short_n",
            (Number::Singular, Gender::Unknown) => return None,
        };
        self.form(key)
    }

    /// Full attributive form for the agreement features.
    pub fn full_form(&self, gender: Gender, case: Case, number: Number) -> Option<&str> {
        let case_key = case_key(case)?;
        let key = match number {
            Number::Plural => format!("{case_key}_pl"),
            Number::Singular => match gender {
                Gender::Masculine => format!("{case_key}_m"),
                Gender::Feminine => format!("{case_key}_f"),
                Gender::Neuter => format!("{case_key}_n"),
                Gender::Unknown => return None,
            },
        };
        self.form(&key)
    }

    pub fn comparative(&self) -> Option<&str> {
        self.form("comp")
    }
}

fn case_key(case: Case) -> Option<&'static str> {
    match case {
        Case::Nominative => Some("nom"),
        Case::Genitive => Some("gen"),
        Case::Dative => Some("dat"),
        Case::Accusative => Some("acc"),
        Case::Instrumental => Some("ins"),
        Case::Prepositional => Some("prep"),
    }
}

fn load_lexicon() -> BTreeMap<String, AdjectiveEntry> {
    let digest = format!("{:x}", Sha256::digest(ADJECTIVE_LEXICON_BYTES));
    assert_eq!(
        digest, ADJECTIVE_LEXICON_SHA256,
        "embedded adjective lexicon digest mismatch: regenerate \
         data/adjective_lexemes.json with scripts/generate_adjective_lexicon.py \
         and update ADJECTIVE_LEXICON_SHA256"
    );
    let file: AdjectiveLexiconFile = serde_json::from_slice(ADJECTIVE_LEXICON_BYTES)
        .expect("embedded adjective lexicon is valid JSON");
    assert_eq!(
        file.schema, ADJECTIVE_LEXICON_SCHEMA,
        "embedded adjective lexicon schema drifted"
    );
    assert_eq!(
        file.lemma_count,
        file.lemmas.len(),
        "embedded adjective lexicon count field disagrees with its entries"
    );
    file.lemmas
        .into_iter()
        .map(|entry| (entry.lemma.clone(), entry))
        .collect()
}

fn lexicon() -> &'static BTreeMap<String, AdjectiveEntry> {
    static LEXICON: OnceLock<BTreeMap<String, AdjectiveEntry>> = OnceLock::new();
    LEXICON.get_or_init(load_lexicon)
}

/// Look up an adjective lemma (masculine nominative) in the embedded table.
pub fn lookup(lemma: &str) -> Option<&'static AdjectiveEntry> {
    lexicon().get(&lemma.to_lowercase())
}

/// Number of adjectives in the embedded lexicon (0 before first lookup).
pub fn lemma_count() -> usize {
    lexicon().len()
}

fn reverse_index() -> &'static BTreeMap<String, Vec<String>> {
    static INDEX: OnceLock<BTreeMap<String, Vec<String>>> = OnceLock::new();
    INDEX.get_or_init(|| {
        let mut index: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for (lemma, entry) in lexicon() {
            for form in entry.forms.values() {
                let lemmas = index.entry(form.clone()).or_default();
                // Two cells of one lemma sharing a surface (gen_m == gen_n)
                // is syncretism, not ambiguity.
                if !lemmas.contains(lemma) {
                    lemmas.push(lemma.clone());
                }
            }
        }
        index
    })
}

/// Resolve a surface form back to its adjective lemma, when unique.
pub fn resolve_surface(surface: &str) -> SurfaceLemma {
    match reverse_index().get(&surface.to_lowercase()) {
        None => SurfaceLemma::Unknown,
        Some(lemmas) if lemmas.len() == 1 => SurfaceLemma::Unique(lemmas[0].as_str()),
        Some(_) => SurfaceLemma::Ambiguous,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lexicon_loads_with_documented_size() {
        assert!(
            lemma_count() >= 20_000,
            "adjective lexicon must be complete"
        );
    }

    #[test]
    fn full_grid_and_short_forms_resolve() {
        let внутренний = lookup("внутренний").expect("внутренний in table");
        assert_eq!(
            внутренний.full_form(Gender::Masculine, Case::Prepositional, Number::Singular),
            Some("внутреннем")
        );
        assert_eq!(
            внутренний.full_form(Gender::Feminine, Case::Genitive, Number::Singular),
            Some("внутренней")
        );
        assert_eq!(
            внутренний.full_form(Gender::Unknown, Case::Nominative, Number::Plural),
            Some("внутренние")
        );

        let необратимый = lookup("необратимый").expect("необратимый in table");
        assert_eq!(
            необратимый.short_form(Gender::Masculine, Number::Singular),
            Some("необратим")
        );
        assert_eq!(
            необратимый.short_form(Gender::Feminine, Number::Singular),
            Some("необратима")
        );
        assert_eq!(
            необратимый.short_form(Gender::Neuter, Number::Singular),
            Some("необратимо")
        );
        assert_eq!(
            необратимый.short_form(Gender::Unknown, Number::Plural),
            Some("необратимы")
        );
    }

    #[test]
    fn surface_resolution_round_trips_and_stays_fail_closed() {
        assert_eq!(
            resolve_surface("внутреннего"),
            SurfaceLemma::Unique("внутренний")
        );
        assert_eq!(
            resolve_surface("необратимому"),
            SurfaceLemma::Unique("необратимый")
        );
        assert_eq!(resolve_surface("фырковистый"), SurfaceLemma::Unknown);
    }

    #[test]
    fn lookup_lowercases_its_input() {
        assert!(lookup("ВНУТРЕННИЙ").is_some());
    }
}
