//! Embedded Russian adjective lexicon, digest-pinned.
//!
//! Generated by `scripts/generate_adjective_lexicon.py` from the pymorphy3
//! OpenCorpora dictionary (see `data/adjective_manifest.json`). Full
//! attributive grid (`{case}_{m,f,n,pl}`), short predicative forms
//! (`short_{m,f,n,pl}`) for qualitative adjectives and the comparative cell
//! (`comp`) where the paradigm has one. The canonical bundle is embedded,
//! verified against a compile-time SHA-256, and precomputed once into
//! `data/adjective_runtime.bin`; the production loader deserializes that
//! blob and fails closed if it does not deserialize — the same policy as
//! the noun `runtime.bin` (ADR-0043 U0.1).
//!
//! The precompute matters for cadence. `serde_json`-parsing the ~50 MB
//! bundle and rebuilding the surface reverse index cost ~1.6 s of CPU in
//! every fresh `qxfx0 turn` process that lemmatizes an adjective surface,
//! which dominated the `input_normalization_ms` tail of the cadence soak.
//! Even a bincode blob of the built `BTreeMap`s still pays ~1 s of per-node
//! allocation on deserialize, so the blob is **flat and zero-copy**: two
//! large string buffers plus POD index vectors. Deserializing it is a pair
//! of `memcpy`s; lookups are binary searches over the sorted buffers.

use qxfx0_types::morphology::{Case, Gender, Number};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;

const ADJECTIVE_LEXICON_BYTES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../data/adjective_lexemes.json"
));

/// Precomputed `data/adjective_runtime.bin`: the lemma table and the surface
/// reverse index in a flat, deserialize-cheap layout. Regenerated by
/// `cargo run -p qxfx0-morphology --example prebuild_adjective_runtime`.
const ADJECTIVE_RUNTIME_BIN: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../data/adjective_runtime.bin"
));

/// SHA-256 of `data/adjective_lexemes.json`, printed by the generator.
const ADJECTIVE_LEXICON_SHA256: &str =
    "52e204deaa2566712a0588f04b58d02a0252d17ddbaa15e14af3066904fe692c";

const ADJECTIVE_LEXICON_SCHEMA: &str = "qxfx0:adjective-lexicon:v1";

#[derive(Debug, Deserialize)]
struct AdjectiveLexiconFile {
    schema: String,
    lemma_count: usize,
    lemmas: Vec<AdjectiveLexiconEntryFile>,
}

#[derive(Debug, Deserialize)]
struct AdjectiveLexiconEntryFile {
    lemma: String,
    forms: BTreeMap<String, String>,
}

/// An adjective's materialized cells, as a copyable view into the
/// process-global precomputed runtime. [`form`] resolves a cell key; the
/// convenience accessors below map agreement features onto keys.
///
/// [`form`]: AdjectiveEntry::form
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AdjectiveEntry {
    /// Masculine nominative lemma.
    pub lemma: &'static str,
    /// Half-open `[start, end)` range of the lemma's cells in the runtime's
    /// interleaved key/value string table, sorted by key.
    cells: (u32, u32),
}

/// Outcome of resolving a surface back to an adjective lemma.
///
/// Ambiguous surfaces (two lemmas share the form) deliberately do not pick a
/// winner: choosing one would fabricate a reading.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SurfaceLemma {
    Unique(&'static str),
    Ambiguous,
    Unknown,
}

impl AdjectiveEntry {
    pub fn form(&self, key: &str) -> Option<&'static str> {
        let runtime = runtime();
        let (start, end) = (self.cells.0 as usize, self.cells.1 as usize);
        for cell in start..end {
            if runtime.cell_str(2 * cell) == key {
                return Some(runtime.cell_str(2 * cell + 1));
            }
        }
        None
    }

    /// Short predicative form for the agreement features, when the paradigm
    /// has one (relational adjectives carry no short forms).
    pub fn short_form(&self, gender: Gender, number: Number) -> Option<&'static str> {
        let key = match (number, gender) {
            (Number::Plural, _) => "short_pl",
            (Number::Singular, Gender::Masculine) => "short_m",
            (Number::Singular, Gender::Feminine) => "short_f",
            (Number::Singular, Gender::Neuter) => "short_n",
            (Number::Singular, Gender::Unknown) => return None,
        };
        self.form(key)
    }

    /// Full attributive form for the agreement features.
    pub fn full_form(&self, gender: Gender, case: Case, number: Number) -> Option<&'static str> {
        let case_key = case_key(case)?;
        let key = match number {
            Number::Plural => format!("{case_key}_pl"),
            Number::Singular => match gender {
                Gender::Masculine => format!("{case_key}_m"),
                Gender::Feminine => format!("{case_key}_f"),
                Gender::Neuter => format!("{case_key}_n"),
                Gender::Unknown => return None,
            },
        };
        self.form(&key)
    }

    pub fn comparative(&self) -> Option<&'static str> {
        self.form("comp")
    }
}

fn case_key(case: Case) -> Option<&'static str> {
    match case {
        Case::Nominative => Some("nom"),
        Case::Genitive => Some("gen"),
        Case::Dative => Some("dat"),
        Case::Accusative => Some("acc"),
        Case::Instrumental => Some("ins"),
        Case::Prepositional => Some("prep"),
    }
}

/// The fully-built adjective lexicon state that the precomputed
/// `data/adjective_runtime.bin` embeds: the lemma table and the
/// surface→lemmas reverse index, in a flat columnar layout.
///
/// Deserializing this struct allocates two large string buffers and a
/// handful of `Vec<u32>`s — no per-string tree nodes — so the load cost
/// tracks `memcpy`, not `BTreeMap` construction. All string tables are
/// sorted, so every lookup is a binary search.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AdjectiveLexiconRuntime {
    /// Concatenated lemma strings, sorted.
    lemma_text: Vec<u8>,
    /// Byte bounds of each lemma; `len() == lemma_count + 1`.
    lemma_bounds: Vec<u32>,
    /// Concatenated cell strings: key, value, key, value… grouped by lemma
    /// (in lemma order) and sorted by key within a lemma.
    cell_text: Vec<u8>,
    /// Byte bounds of each cell string; `len() == 2 * cell_count + 1`.
    cell_bounds: Vec<u32>,
    /// Per-lemma cell-count bounds; `len() == lemma_count + 1`.
    cell_offsets: Vec<u32>,
    /// Concatenated surface strings, sorted.
    surface_text: Vec<u8>,
    /// Byte bounds of each surface; `len() == surface_count + 1`.
    surface_bounds: Vec<u32>,
    /// Flattened lemma indices referenced by each surface.
    reverse_values: Vec<u32>,
    /// Per-surface value-count bounds; `len() == surface_count + 1`.
    reverse_offsets: Vec<u32>,
}

impl AdjectiveLexiconRuntime {
    fn str_at<'a>(text: &'a [u8], bounds: &[u32], index: usize) -> &'a str {
        let start = bounds[index] as usize;
        let end = bounds[index + 1] as usize;
        std::str::from_utf8(&text[start..end]).expect("stored strings are valid UTF-8")
    }

    /// Binary search a sorted, bounds-indexed string table.
    fn sorted_find(text: &[u8], bounds: &[u32], count: usize, target: &str) -> Option<usize> {
        let mut low = 0usize;
        let mut high = count;
        while low < high {
            let mid = (low + high) / 2;
            if Self::str_at(text, bounds, mid) < target {
                low = mid + 1;
            } else {
                high = mid;
            }
        }
        (low < count && Self::str_at(text, bounds, low) == target).then_some(low)
    }

    /// Number of adjective lemmas in the table.
    pub fn lemma_count(&self) -> usize {
        self.lemma_bounds.len() - 1
    }

    /// Number of distinct indexed surfaces.
    pub fn surface_count(&self) -> usize {
        self.surface_bounds.len() - 1
    }

    fn lemma_str(&self, index: usize) -> &str {
        Self::str_at(&self.lemma_text, &self.lemma_bounds, index)
    }

    fn cell_str(&self, index: usize) -> &str {
        Self::str_at(&self.cell_text, &self.cell_bounds, index)
    }

    fn find_lemma(&self, lemma: &str) -> Option<usize> {
        Self::sorted_find(
            &self.lemma_text,
            &self.lemma_bounds,
            self.lemma_count(),
            lemma,
        )
    }

    fn find_surface(&self, surface: &str) -> Option<usize> {
        Self::sorted_find(
            &self.surface_text,
            &self.surface_bounds,
            self.surface_count(),
            surface,
        )
    }
}

/// Digest-check and parse the canonical embedded `adjective_lexemes.json`
/// into the fully-built flat runtime (lemma table + reverse index). Used by
/// the prebuild example, the blob-parity test and the runtime fallback path.
pub fn build_runtime_from_embedded_json() -> AdjectiveLexiconRuntime {
    let digest = format!("{:x}", Sha256::digest(ADJECTIVE_LEXICON_BYTES));
    assert_eq!(
        digest, ADJECTIVE_LEXICON_SHA256,
        "embedded adjective lexicon digest mismatch: regenerate \
         data/adjective_lexemes.json with scripts/generate_adjective_lexicon.py \
         and update ADJECTIVE_LEXICON_SHA256"
    );
    let file: AdjectiveLexiconFile = serde_json::from_slice(ADJECTIVE_LEXICON_BYTES)
        .expect("embedded adjective lexicon is valid JSON");
    assert_eq!(
        file.schema, ADJECTIVE_LEXICON_SCHEMA,
        "embedded adjective lexicon schema drifted"
    );
    assert_eq!(
        file.lemma_count,
        file.lemmas.len(),
        "embedded adjective lexicon count field disagrees with its entries"
    );

    // Build the ordered tables first (prebuild-time cost only), then flatten.
    let lexicon: BTreeMap<String, BTreeMap<String, String>> = file
        .lemmas
        .into_iter()
        .map(|entry| (entry.lemma, entry.forms))
        .collect();
    let mut reverse: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (lemma, forms) in &lexicon {
        for form in forms.values() {
            let lemmas = reverse.entry(form.clone()).or_default();
            // Two cells of one lemma sharing a surface (gen_m == gen_n)
            // is syncretism, not ambiguity.
            if !lemmas.contains(lemma) {
                lemmas.push(lemma.clone());
            }
        }
    }

    let mut lemma_text = Vec::new();
    let mut lemma_bounds = vec![0u32];
    let mut cell_text = Vec::new();
    let mut cell_bounds = vec![0u32];
    let mut cell_offsets = vec![0u32];
    let mut lemma_ids: BTreeMap<&str, u32> = BTreeMap::new();
    for (index, (lemma, forms)) in lexicon.iter().enumerate() {
        lemma_ids.insert(lemma.as_str(), index as u32);
        lemma_text.extend_from_slice(lemma.as_bytes());
        lemma_bounds.push(lemma_text.len() as u32);
        for (key, value) in forms {
            cell_text.extend_from_slice(key.as_bytes());
            cell_bounds.push(cell_text.len() as u32);
            cell_text.extend_from_slice(value.as_bytes());
            cell_bounds.push(cell_text.len() as u32);
        }
        cell_offsets.push(((cell_bounds.len() - 1) / 2) as u32);
    }

    let mut surface_text = Vec::new();
    let mut surface_bounds = vec![0u32];
    let mut reverse_values = Vec::new();
    let mut reverse_offsets = vec![0u32];
    for (surface, lemmas) in &reverse {
        surface_text.extend_from_slice(surface.as_bytes());
        surface_bounds.push(surface_text.len() as u32);
        for lemma in lemmas {
            reverse_values.push(lemma_ids[lemma.as_str()]);
        }
        reverse_offsets.push(reverse_values.len() as u32);
    }

    AdjectiveLexiconRuntime {
        lemma_text,
        lemma_bounds,
        cell_text,
        cell_bounds,
        cell_offsets,
        surface_text,
        surface_bounds,
        reverse_values,
        reverse_offsets,
    }
}

/// Deserialize the embedded precomputed adjective runtime blob.
pub fn load_runtime_from_embedded_blob() -> Result<AdjectiveLexiconRuntime, String> {
    bincode::deserialize(ADJECTIVE_RUNTIME_BIN)
        .map_err(|error| format!("adjective runtime.bin: {error}"))
}

static ADJECTIVE_RUNTIME_INIT_MS: AtomicU64 = AtomicU64::new(0);

/// One-time cost (ms) of making the adjective lexicon usable in this process:
/// blob deserialize on the happy path, JSON parse + flatten on the fallback.
/// Zero when no adjective surface is ever resolved. Attribute for
/// `input_normalization_ms` spikes that `morphology_init_ms` does not cover.
pub fn adjective_lexicon_init_ms() -> u64 {
    ADJECTIVE_RUNTIME_INIT_MS.load(Ordering::Relaxed)
}

fn runtime() -> &'static AdjectiveLexiconRuntime {
    static RUNTIME: OnceLock<AdjectiveLexiconRuntime> = OnceLock::new();
    RUNTIME.get_or_init(|| {
        let started = std::time::Instant::now();
        let runtime = runtime_or_panic(load_runtime_from_embedded_blob());
        ADJECTIVE_RUNTIME_INIT_MS.store(
            u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX),
            Ordering::Relaxed,
        );
        runtime
    })
}

/// Fail-closed blob init (ADR-0043 U0.1): a blob that does not deserialize is
/// a build-integrity failure, not a slow-turn trigger. The JSON-parse fallback
/// is deliberately gone — it silently reintroduced the ~1.6 s parse that the
/// precompute removed.
fn runtime_or_panic(result: Result<AdjectiveLexiconRuntime, String>) -> AdjectiveLexiconRuntime {
    result.unwrap_or_else(|error| {
        panic!(
            "embedded adjective runtime.bin failed to deserialize ({error}); \
             regenerate with `cargo run -p qxfx0-morphology --example \
             prebuild_adjective_runtime` and commit it together with \
             data/adjective_lexemes.json (ADR-0043 U0.1: fail-closed, \
             no JSON-parse fallback)"
        )
    })
}

/// Look up an adjective lemma (masculine nominative) in the embedded table.
/// The returned entry is a copyable view; it stays valid for the process
/// lifetime.
pub fn lookup(lemma: &str) -> Option<AdjectiveEntry> {
    let runtime = runtime();
    let index = runtime.find_lemma(&lemma.to_lowercase())?;
    Some(AdjectiveEntry {
        lemma: runtime.lemma_str(index),
        cells: (runtime.cell_offsets[index], runtime.cell_offsets[index + 1]),
    })
}

/// Number of adjectives in the embedded lexicon (0 before first lookup).
pub fn lemma_count() -> usize {
    runtime().lemma_count()
}

/// Resolve a surface form back to its adjective lemma, when unique.
pub fn resolve_surface(surface: &str) -> SurfaceLemma {
    let runtime = runtime();
    let lower = surface.to_lowercase();
    let Some(index) = runtime.find_surface(&lower) else {
        return SurfaceLemma::Unknown;
    };
    let start = runtime.reverse_offsets[index] as usize;
    let end = runtime.reverse_offsets[index + 1] as usize;
    if end - start == 1 {
        SurfaceLemma::Unique(runtime.lemma_str(runtime.reverse_values[start] as usize))
    } else {
        SurfaceLemma::Ambiguous
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lexicon_loads_with_documented_size() {
        assert!(
            lemma_count() >= 20_000,
            "adjective lexicon must be complete"
        );
    }

    #[test]
    fn full_grid_and_short_forms_resolve() {
        let внутренний = lookup("внутренний").expect("внутренний in table");
        assert_eq!(
            внутренний.full_form(Gender::Masculine, Case::Prepositional, Number::Singular),
            Some("внутреннем")
        );
        assert_eq!(
            внутренний.full_form(Gender::Feminine, Case::Genitive, Number::Singular),
            Some("внутренней")
        );
        assert_eq!(
            внутренний.full_form(Gender::Unknown, Case::Nominative, Number::Plural),
            Some("внутренние")
        );

        let необратимый = lookup("необратимый").expect("необратимый in table");
        assert_eq!(
            необратимый.short_form(Gender::Masculine, Number::Singular),
            Some("необратим")
        );
        assert_eq!(
            необратимый.short_form(Gender::Feminine, Number::Singular),
            Some("необратима")
        );
        assert_eq!(
            необратимый.short_form(Gender::Neuter, Number::Singular),
            Some("необратимо")
        );
        assert_eq!(
            необратимый.short_form(Gender::Unknown, Number::Plural),
            Some("необратимы")
        );
    }

    #[test]
    fn surface_resolution_round_trips_and_stays_fail_closed() {
        assert_eq!(
            resolve_surface("внутреннего"),
            SurfaceLemma::Unique("внутренний")
        );
        assert_eq!(
            resolve_surface("необратимому"),
            SurfaceLemma::Unique("необратимый")
        );
        assert_eq!(resolve_surface("фырковистый"), SurfaceLemma::Unknown);
    }

    // --- ADR-0043 U0.1: fail-closed blob init ---

    #[test]
    #[should_panic(expected = "ADR-0043 U0.1: fail-closed, no JSON-parse fallback")]
    fn corrupt_adjective_blob_panics_instead_of_json_fallback() {
        let _ = runtime_or_panic(Err("simulated corruption".to_string()));
    }

    #[test]
    fn lookup_lowercases_its_input() {
        assert!(lookup("ВНУТРЕННИЙ").is_some());
    }

    #[test]
    fn embedded_adjective_runtime_blob_matches_the_json_lexicon() {
        let from_blob = load_runtime_from_embedded_blob()
            .expect("embedded adjective runtime.bin must deserialize");
        assert!(
            from_blob.lemma_count() > 0 && from_blob.surface_count() > 0,
            "the precomputed blob must carry both the lemma table and the index"
        );
        assert_eq!(
            from_blob,
            build_runtime_from_embedded_json(),
            "data/adjective_runtime.bin is stale: re-run \
             cargo run -p qxfx0-morphology --example prebuild_adjective_runtime"
        );
    }

    #[test]
    fn entries_survive_a_second_lookup_after_the_first_dropped() {
        let first = lookup("внутренний").expect("entry");
        // AdjectiveEntry is Copy: this only ends the first binding's use, the
        // underlying view must stay valid for the process lifetime.
        let _ = first;
        let second = lookup("внутренний").expect("entry");
        assert_eq!(second.form("prep_m"), Some("внутреннем"));
    }
}
