//! Embedded Russian pronoun lexicon, digest-pinned.
//!
//! Generated by `scripts/generate_pronoun_lexicon.py` from the pymorphy3
//! OpenCorpora dictionary (see `data/pronoun_manifest.json`). Pronouns are a
//! closed class but the class declines: personal pronouns carry a six-case
//! paradigm, adjective-type pronouns (possessive, demonstrative,
//! determinative, relative) carry gendered forms. The tables are materialized
//! from the dictionary rather than hand-maintained so the Rust runtime and
//! the Python corpus tooling share one source of truth.

use qxfx0_types::morphology::{Case, Gender, Number};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::sync::OnceLock;

const PRONOUN_LEXICON_BYTES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../data/pronoun_lexemes.json"
));

/// SHA-256 of `data/pronoun_lexemes.json`, printed by the generator.
const PRONOUN_LEXICON_SHA256: &str =
    "84818c2d3a87c8abf24cc8f5963eb6cd40a8af1b0c9a543141831d6e07415990";

const PRONOUN_LEXICON_SCHEMA: &str = "qxfx0:pronoun-lexicon:v1";

#[derive(Debug, Deserialize)]
struct PronounLexiconFile {
    schema: String,
    lemma_count: usize,
    lemmas: Vec<PronounEntry>,
}

/// One pronoun's materialized cells.
#[derive(Debug, Clone, Deserialize)]
pub struct PronounEntry {
    pub lemma: String,
    pub forms: BTreeMap<String, String>,
}

/// Outcome of resolving a surface back to a pronoun lemma; ambiguous
/// surfaces deliberately do not pick a winner.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PronounSurface {
    Unique(&'static str),
    Ambiguous,
    Unknown,
}

impl PronounEntry {
    pub fn form(&self, key: &str) -> Option<&str> {
        self.forms.get(key).map(String::as_str)
    }

    /// Ungendered cell (`себя`-style paradigm).
    pub fn case_form(&self, case: Case, number: Number) -> Option<&str> {
        let case_key = case_key(case)?;
        let key = match number {
            Number::Singular => format!("{case_key}_sg"),
            Number::Plural => format!("{case_key}_pl"),
        };
        self.form(&key)
    }

    /// Gendered cell (adjective-type pronouns).
    pub fn gendered_form(&self, case: Case, gender: Gender) -> Option<&str> {
        let case_key = case_key(case)?;
        let gender_key = match gender {
            Gender::Masculine => "m",
            Gender::Feminine => "f",
            Gender::Neuter => "n",
            Gender::Unknown => return None,
        };
        self.form(&format!("{case_key}_sg_{gender_key}"))
    }
}

fn case_key(case: Case) -> Option<&'static str> {
    match case {
        Case::Nominative => Some("nom"),
        Case::Genitive => Some("gen"),
        Case::Dative => Some("dat"),
        Case::Accusative => Some("acc"),
        Case::Instrumental => Some("ins"),
        Case::Prepositional => Some("prep"),
    }
}

fn load_lexicon() -> BTreeMap<String, PronounEntry> {
    let digest = format!("{:x}", Sha256::digest(PRONOUN_LEXICON_BYTES));
    assert_eq!(
        digest, PRONOUN_LEXICON_SHA256,
        "embedded pronoun lexicon digest mismatch: regenerate \
         data/pronoun_lexemes.json with scripts/generate_pronoun_lexicon.py \
         and update PRONOUN_LEXICON_SHA256"
    );
    let file: PronounLexiconFile = serde_json::from_slice(PRONOUN_LEXICON_BYTES)
        .expect("embedded pronoun lexicon is valid JSON");
    assert_eq!(
        file.schema, PRONOUN_LEXICON_SCHEMA,
        "embedded pronoun lexicon schema drifted"
    );
    assert_eq!(
        file.lemma_count,
        file.lemmas.len(),
        "embedded pronoun lexicon count field disagrees with its entries"
    );
    file.lemmas
        .into_iter()
        .map(|entry| (entry.lemma.clone(), entry))
        .collect()
}

fn lexicon() -> &'static BTreeMap<String, PronounEntry> {
    static LEXICON: OnceLock<BTreeMap<String, PronounEntry>> = OnceLock::new();
    LEXICON.get_or_init(load_lexicon)
}

/// Look up a pronoun lemma in the embedded table.
pub fn lookup(lemma: &str) -> Option<&'static PronounEntry> {
    lexicon().get(&lemma.to_lowercase())
}

/// Number of pronouns in the embedded lexicon (0 before first lookup).
pub fn lemma_count() -> usize {
    lexicon().len()
}

/// Resolve a surface form back to its pronoun lemma, when unique.
///
/// Homonymy with other closed classes (the particle «то», the conjunction
/// «а»-likes) is resolved by this table only claiming forms that the
/// dictionary itself parses as pronoun cells.
pub fn resolve_surface(surface: &str) -> PronounSurface {
    static INDEX: OnceLock<BTreeMap<String, Vec<String>>> = OnceLock::new();
    let index = INDEX.get_or_init(|| {
        let mut index: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for (lemma, entry) in lexicon() {
            for form in entry.forms.values() {
                let lemmas = index.entry(form.clone()).or_default();
                // Syncretism inside one paradigm is not ambiguity.
                if !lemmas.contains(lemma) {
                    lemmas.push(lemma.clone());
                }
            }
        }
        index
    });
    match index.get(&surface.to_lowercase()) {
        None => PronounSurface::Unknown,
        Some(lemmas) if lemmas.len() == 1 => {
            // The index borrows from the process-wide lexicon; the unique
            // lemma is recovered through the table, not stored twice.
            let unique = &lemmas[0];
            let entry = lexicon().get(unique).expect("index mirrors lexicon");
            PronounSurface::Unique(entry_lemma(entry))
        }
        Some(_) => PronounSurface::Ambiguous,
    }
}

fn entry_lemma(entry: &'static PronounEntry) -> &'static str {
    &entry.lemma
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn closed_class_loads_completely() {
        assert!(
            lemma_count() >= 40,
            "pronoun lexicon covers the closed class"
        );
        for expected in ["я", "ты", "он", "мы", "вы", "они", "себя", "весь", "сам"]
        {
            assert!(lookup(expected).is_some(), "{expected} missing");
        }
    }

    #[test]
    fn personal_pronouns_decline() {
        let я = lookup("я").expect("я in table");
        assert_eq!(я.case_form(Case::Nominative, Number::Singular), Some("я"));
        assert_eq!(я.case_form(Case::Genitive, Number::Singular), Some("меня"));
        assert_eq!(я.case_form(Case::Dative, Number::Singular), Some("мне"));
        assert_eq!(
            я.case_form(Case::Instrumental, Number::Singular),
            Some("мной")
        );

        let себя = lookup("себя").expect("себя in table");
        assert_eq!(
            себя.case_form(Case::Genitive, Number::Singular),
            Some("себя")
        );
        assert_eq!(
            себя.case_form(Case::Prepositional, Number::Singular),
            Some("себе")
        );
    }

    #[test]
    fn gendered_pronouns_agree() {
        let весь = lookup("весь").expect("весь in table");
        assert_eq!(
            весь.gendered_form(Case::Nominative, Gender::Masculine),
            Some("весь")
        );
        assert_eq!(
            весь.gendered_form(Case::Nominative, Gender::Feminine),
            Some("вся")
        );
        assert_eq!(
            весь.gendered_form(Case::Nominative, Gender::Neuter),
            Some("всё")
        );
        assert_eq!(
            весь.case_form(Case::Instrumental, Number::Plural),
            Some("всеми")
        );
    }

    #[test]
    fn surface_resolution_is_fail_closed() {
        assert_eq!(resolve_surface("собой"), PronounSurface::Unique("себя"));
        assert_eq!(resolve_surface("мной"), PronounSurface::Unique("я"));
        assert_eq!(resolve_surface("внутреннего"), PronounSurface::Unknown);
    }
}
