//! Embedded Russian verb lexicon, digest-pinned.
//!
//! Generated by `scripts/generate_verb_lexicon.py` from the pymorphy3
//! OpenCorpora dictionary (see `data/verb_manifest.json`). 30 809 verb
//! infinitives — non-reflexive and reflexive — with person, past and
//! imperative cells. The bundle is embedded, verified against a compile-time
//! SHA-256 and parsed once per process — the same policy as the noun lexicon
//! bundle.
//!
//! The rule engine in `crate::verbs` consults this table first; rules stay
//! the fallback for lemmas the dictionary does not carry.

use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::sync::OnceLock;

const VERB_LEXICON_BYTES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../data/verb_lexemes.json"
));

/// SHA-256 of `data/verb_lexemes.json`, printed by the generator.
const VERB_LEXICON_SHA256: &str =
    "2e8e80ff0219f7a2def77e01d41cee13a3de408642cdb48ed289fe6e6e411ac1";

const VERB_LEXICON_SCHEMA: &str = "qxfx0:verb-lexicon:v1";

#[derive(Debug, Deserialize)]
struct VerbLexiconFile {
    schema: String,
    lemma_count: usize,
    lemmas: Vec<VerbEntry>,
}

/// One verb's materialized cells.
#[derive(Debug, Clone, Deserialize)]
pub struct VerbEntry {
    pub lemma: String,
    pub aspect: String,
    pub forms: BTreeMap<String, String>,
}

impl VerbEntry {
    pub fn form(&self, key: &str) -> Option<&str> {
        self.forms.get(key).map(String::as_str)
    }

    pub fn aspect(&self) -> &str {
        &self.aspect
    }
}

fn load_lexicon() -> BTreeMap<String, VerbEntry> {
    let digest = format!("{:x}", Sha256::digest(VERB_LEXICON_BYTES));
    assert_eq!(
        digest, VERB_LEXICON_SHA256,
        "embedded verb lexicon digest mismatch: regenerate data/verb_lexemes.json \
         with scripts/generate_verb_lexicon.py and update VERB_LEXICON_SHA256"
    );
    let file: VerbLexiconFile =
        serde_json::from_slice(VERB_LEXICON_BYTES).expect("embedded verb lexicon is valid JSON");
    assert_eq!(
        file.schema, VERB_LEXICON_SCHEMA,
        "embedded verb lexicon schema drifted"
    );
    assert_eq!(
        file.lemma_count,
        file.lemmas.len(),
        "embedded verb lexicon count field disagrees with its entries"
    );
    file.lemmas
        .into_iter()
        .map(|entry| (entry.lemma.clone(), entry))
        .collect()
}

/// Look up an infinitive in the embedded verb table.
pub fn lookup(infinitive: &str) -> Option<&'static VerbEntry> {
    static LEXICON: OnceLock<BTreeMap<String, VerbEntry>> = OnceLock::new();
    LEXICON
        .get_or_init(load_lexicon)
        .get(&infinitive.to_lowercase())
}

/// Number of verbs in the embedded lexicon (0 before first lookup).
pub fn lemma_count() -> usize {
    static LEXICON: OnceLock<BTreeMap<String, VerbEntry>> = OnceLock::new();
    LEXICON.get_or_init(load_lexicon).len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lexicon_loads_with_documented_size() {
        assert!(lemma_count() >= 19_000, "verb lexicon must be complete");
    }

    #[test]
    fn alternating_verbs_are_table_backed() {
        // These are exactly the verbs the rule engine must refuse.
        let писать = lookup("писать").expect("писать in table");
        assert_eq!(писать.form("f1sg"), Some("пишу"));
        assert_eq!(писать.form("f3pl"), Some("пишут"));

        let жить = lookup("жить").expect("жить in table");
        assert_eq!(жить.form("f1sg"), Some("живу"));
        assert_eq!(жить.form("ppl"), Some("жили"));

        let любить = lookup("любить").expect("любить in table");
        assert_eq!(любить.form("f1sg"), Some("люблю"));
        assert_eq!(любить.form("f3pl"), Some("любят"));

        let терпеть = lookup("терпеть").expect("терпеть in table");
        assert_eq!(терпеть.form("f1sg"), Some("терплю"));
        assert_eq!(терпеть.form("f3pl"), Some("терпят"));

        let смотреть = lookup("смотреть").expect("смотреть in table");
        assert_eq!(смотреть.form("f1sg"), Some("смотрю"));
        assert_eq!(смотреть.form("f3pl"), Some("смотрят"));
    }

    #[test]
    fn aspects_and_infinitives_are_recorded() {
        assert_eq!(lookup("делать").unwrap().aspect(), "impf");
        assert_eq!(lookup("сделать").unwrap().aspect(), "perf");
        assert_eq!(lookup("делать").unwrap().form("f1sg"), Some("делаю"));
        // Perfective persons are future cells.
        assert_eq!(lookup("сделать").unwrap().form("f1sg"), Some("сделаю"));
    }

    #[test]
    fn unknown_verbs_are_absent() {
        assert!(lookup("фырковать").is_none());
        assert!(lookup("").is_none());
        // Lookup lowercases its input.
        assert!(lookup("ДЕЛАТЬ").is_some());
    }
}
